# .github/workflows/main.yml
# Copy/pasted from https://angular.io/guide/testing#configure-project-for-github-actions
name: CI Nest.js app through Github Actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Setup
        run: npm ci

      - name: Test
        run: |
          npm test

      - name: E2E Test
        run: |
          npm test:e2e
